name: Auto Assign Reviewers and Assignees

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto_assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto Assign Reviewers and Assignees
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: memory-h, z00m-1n, jang9465, Lee-gi-yeun, jihye25
